#pragma once

namespace Engine
{
	enum class AREAMGR { STATION, HOTEL, FUOCO, OUTER, DEBUG, END };

	enum class COLLIDER { AABB, OBB, SPHERE, END };
	enum class MODEL { NONANIM, ANIM };
	enum class DIM { LBUTTON, RBUTTON, WHEELBUTTON };
	enum class DIMM { X, Y, WHEEL };
	enum class D3DTS { VIEW, PROJ, END };

	enum class FrustumHit { Outside, Intersect, Inside };
	enum class OCTOTREEOBJECTTYPE { MESH, LIGHT, END };

	enum class RENDERGROUP{ RG_PRIORITY, RG_SHADOW, RG_NONBLEND, RG_PBRMESH, RG_DECAL, RG_NONLIGHT, RG_BLEND,
							RG_EFFECT_GLOW, RG_EFFECT_WB, RG_EFFECT_NL, RG_EFFECT_LIGHT, RG_EFFECT_END,
							RG_UI, RG_UI_DEFERRED, RG_FURY, RG_LIMLIGHT, RG_BURN, RG_WATERPUDDLE, RG_END };
	enum class DEFEREDPASS {
		DEBUG, LIGHT_DIRECTIONAL, LIGHT_POINT, DEFERRED, BLURX, BLURY,
		PBR_LIGHT_POINT, PBR_LIGHT_DIRECTION, VIGNETTING,
		VOLUMETRIC_POINT, VOLUMETRIC_DIRECTION, PBR_LIGHT_SPOT, VOLUMETRIC_SPOT,
		EFFECT_GLOW, DOWNSCALE, WB_COMPOSITE, DISTORTION, DOF_ROUND
	};

	enum class PROTOTYPE { TYPE_GAMEOBJECT, TYPE_COMPONENT };
	enum class STATE { RIGHT, UP, LOOK, POSITION, END };

	enum class SHADOW { SHADOWA, SHADOWB, SHADOWC, SHADOW_END };

	enum WORLDFILTER
	{
		FILTER_PLAYERBODY = 1 << 0,
		FILTER_PLAYERWEAPON = 1 << 1,
		FILTER_MONSTERBODY = 1 << 2,
		FILTER_MONSTERWEAPON = 1 << 3,
		FILTER_EFFECTGIB = 1 << 4,
		FILTER_DYNAMICOBJ = 1 << 5,
		FILTER_NPC = 1 << 6,
		FILTER_MAP = 1 << 7,
		FILTER_INTERACT = 1 << 8,
		FILTER_FLOOR = 1 << 9, //중력받는 것들이 FILTER_MAP과 모두 충돌검사하니 렉걸린다. 그래서 바닥이라는 필터를 만듬
	};

	enum class COLLIDERTYPE 
	{
		PLAYER,
		TRIGGER,
		MONSTER,
		PLAYER_WEAPON,
		MONSTER_WEAPON,
		MONSTER_WEAPON_BODY,
		BOSS_WEAPON,
		BOSS_PROJECTILE,
		MONSTER_PROJECTILE,
		NPC,
		ENVIRONMENT_CONVEX,
		ENVIRONMENT_TRI,
		BREAKABLE_OBJECT, //부술 수 있는 오브젝트(푸오코 기둥 등 부서지는 오브젝트)
		A,
		B,
		C,
		D,
		E,
	};


	enum class ParamType { Bool, Trigger, Float, Int};

	enum PARTICLETYPE { PTYPE_SPREAD, PTYPE_DIRECTIONAL, PTYPE_ALLRANDOM, PTYPE_SHRINK, PTYPE_END };

}