#pragma once


namespace Client
{
	enum class LEVEL { STATIC, LOADING, LOGO, KRAT_CENTERAL_STATION,YG, CY, GL, DH, YW, JW,END };

	enum UI_PASS_INDEX { UI_DEFAULT = 0, UI_SOFTEFFECT, UI_DISCARD_DARK, UI_DISCARD_ALAPH, 
						UI_BLEND, UI_BLEND_DISCARD_ALAPH, UI_BLEND_DISCARD_DARK, UI_FADE,
						UI_VIGNETTING,
						UI_END};
}


