#pragma once


namespace Client
{
	enum class LEVEL { STATIC, LOADING, LOGO, KRAT_CENTERAL_STATION, KRAT_HOTEL, YG, CY, GL, DH, YW, JW,END };


#pragma region CY
	enum EFFECT_PASS_INDEX { EFF_DEFAULT, EFF_SOFTEFFECT, EFF_UVSPRITE, EFF_UVSPRITE_COLOR, EFF_END };

	enum INTERPOLATION {
		INTERPOLATION_LERP,
		INTERPOLATION_EASEOUTBACK,
		INTERPOLATION_EASEOUTCUBIC,
		INTERPOLATION_EASEINQUAD,
		INTERPOLATION_EASEOUTQUAD,
		INTERPOLATION_END
	};
#pragma endregion

#pragma region GL
	enum UI_PASS_INDEX { UI_DEFAULT = 0, UI_SOFTEFFECT, UI_DISCARD_DARK, UI_DISCARD_ALAPH, 
						UI_BLEND, UI_BLEND_DISCARD_ALAPH, UI_BLEND_DISCARD_DARK, UI_FADE,
						UI_VIGNETTING,
						UI_END};

	enum DYNAMIC_UI_PASS_INDEX {
		D_UI_DEFAULT = 0, D_UI_SOFTEFFECT, D_UI_SPRITE, D_UI_FADE,
		D_UI_BUTTON,
		D_UI_END
	};

#pragma endregion

	enum INTERPOLATION_CAMERA
	{
		NONE,
		LERP,
		CATMULLROM
	};
}


